Joao mendonca/button component
LohanBatista/appToDoLCode pull request #7
Opened 2023-02-28 17:37 UTC by P3dro-4rtur

2023-02-28 17:42 UTC, LohanBatista requested changes

2023-02-28 17:42 UTC, LohanBatista commented on ToDoApp/src/components/ButtonComponent/styles.ts
> +  color: '#ffff',
usar cores to TEMA

2023-02-28 17:42 UTC, LohanBatista commented on ToDoApp/src/screens/Home/styles.ts
> +import {ButtonComponent} from '~/components/ButtonComponent';
isso não vai ser utilizado aqui

2023-02-28 17:42 UTC, LohanBatista commented on ToDoApp/src/screens/Home/styles.ts
> +export const Button = styled(ButtonComponent)``;
isso não vai ser utilizado aqui

2023-03-01 12:58 UTC, Joao-Vitor97 commented on ToDoApp/src/components/ButtonComponent/styles.ts
> +  color: '#ffff',
Corrigido

2023-03-01 12:59 UTC, Joao-Vitor97 commented on ToDoApp/src/screens/Home/styles.ts
> +import {ButtonComponent} from '~/components/ButtonComponent';
Corrigido, retirado os imports não necessários.

2023-03-01 12:59 UTC, Joao-Vitor97 commented on ToDoApp/src/screens/Home/styles.ts
> +export const Button = styled(ButtonComponent)``;
Corrigido.

2023-03-01 13:24 UTC, LohanBatista approved these changes

2023-03-01 13:26 UTC, merged